# -*- coding: utf-8 -*-
"""
build_full_3000.py
Compiles exactly 3000 common English words (Oxford 3000) with full Vietnamese translations,
IPA phonetics, examples, levels (A1, A2, B1), and 16 topics.
"""

import json
import os

# Comprehensive list of 3000 most common English words
# Grouped by themes, roots, and frequency tiers

# 1. Base dictionary of 3000 words with Vietnamese translations, IPA approximations, and examples
oxford_3000_raw = [
    # Top 100 Most Essential (A1)
    ("the", "/ðə/", "art", "cái, người, sự (mạo từ xác định)", "The sun rises in the east.", "Mặt trời mọc ở hướng đông.", "A1", "Đời sống"),
    ("be", "/biː/", "v", "thì, là, ở", "Be happy and kind to others.", "Hãy vui vẻ và tốt bụng với người khác.", "A1", "Đời sống"),
    ("to", "/tuː/", "prep", "đến, để", "I go to school by bus.", "Tôi đi đến trường bằng xe buýt.", "A1", "Đời sống"),
    ("of", "/əv/", "prep", "của, thuộc về", "A cup of hot coffee.", "Một tách cà phê nóng.", "A1", "Ăn uống"),
    ("and", "/ænd/", "conj", "và", "You and me are friends.", "Bạn và tôi là bạn bè.", "A1", "Chào hỏi & Giao tiếp"),
    ("a", "/ə/", "art", "một (mạo từ không xác định)", "I have a green apple.", "Tôi có một quả táo màu xanh.", "A1", "Đời sống"),
    ("in", "/ɪn/", "prep", "trong, ở trong", "The book is in my bag.", "Quyển sách ở trong cặp của tôi.", "A1", "Nhà cửa & Đồ vật"),
    ("that", "/ðæt/", "pron, conj", "cái đó, rằng", "That is my new bicycle.", "Đó là chiếc xe đạp mới của tôi.", "A1", "Đời sống"),
    ("have", "/hæv/", "v", "có, sở hữu", "I have two brothers.", "Tôi có hai người anh trai.", "A1", "Gia đình"),
    ("I", "/aɪ/", "pron", "tôi", "I am learning English.", "Tôi đang học tiếng Anh.", "A1", "Chào hỏi & Giao tiếp"),
    ("it", "/ɪt/", "pron", "nó (chỉ sự vật)", "It is raining outside.", "Trời đang mưa bên ngoài.", "A1", "Thời tiết & Thiên nhiên"),
    ("for", "/fɔː(r)/", "prep", "cho, dành cho", "This present is for you.", "Món quà này là dành cho bạn.", "A1", "Đời sống"),
    ("not", "/nɒt/", "adv", "không", "I do not understand.", "Tôi không hiểu.", "A1", "Chào hỏi & Giao tiếp"),
    ("on", "/ɒn/", "prep", "trên, ở trên", "The cup is on the table.", "Cái tách ở trên bàn.", "A1", "Nhà cửa & Đồ vật"),
    ("with", "/wɪð/", "prep", "với, cùng với", "Come with us to the park.", "Hãy đi cùng chúng tôi tới công viên.", "A1", "Đời sống"),
    ("he", "/hiː/", "pron", "anh ấy, ông ấy", "He is a good doctor.", "Anh ấy là một bác sĩ giỏi.", "A1", "Gia đình"),
    ("as", "/æz/", "prep, conj", "như, bởi vì", "Do as I said.", "Hãy làm như tôi đã nói.", "A1", "Đời sống"),
    ("you", "/juː/", "pron", "bạn, các bạn", "How do you feel today?", "Hôm nay bạn cảm thấy thế nào?", "A1", "Chào hỏi & Giao tiếp"),
    ("do", "/duː/", "v", "làm, thực hiện", "What do you do every day?", "Bạn làm gì mỗi ngày?", "A1", "Công việc & Công sở"),
    ("at", "/æt/", "prep", "ở tại (thời gian, địa điểm)", "I meet you at 8 o'clock.", "Tôi gặp bạn lúc 8 giờ.", "A1", "Thời gian & Ngày tháng"),
    ("this", "/ðɪs/", "pron", "cái này, người này", "This shirt looks great.", "Chiếc áo này trông rất tuyệt.", "A1", "Mua sắm"),
    ("but", "/bʌt/", "conj", "nhưng, nhưng mà", "It is small but nice.", "Nó nhỏ nhưng đẹp.", "A1", "Đời sống"),
    ("his", "/hɪz/", "det, pron", "của anh ấy", "His car is white.", "Xe ô tô của anh ấy màu trắng.", "A1", "Gia đình"),
    ("by", "/baɪ/", "prep", "bởi, bằng phương tiện", "Travel by plane is fast.", "Đi bằng máy bay thì nhanh.", "A1", "Đi lại & Du lịch"),
    ("from", "/frɒm/", "prep", "từ đâu đến", "I come from Vietnam.", "Tôi đến từ Việt Nam.", "A1", "Chào hỏi & Giao tiếp"),
    ("they", "/ðeɪ/", "pron", "họ, chúng nó", "They are playing soccer.", "Họ đang chơi đá bóng.", "A1", "Thể thao & Giải trí"),
    ("we", "/wiː/", "pron", "chúng tôi, chúng ta", "We love our country.", "Chúng tôi yêu đất nước của mình.", "A1", "Đời sống"),
    ("say", "/seɪ/", "v", "nói rằng", "What did you say?", "Bạn đã nói gì vậy?", "A1", "Chào hỏi & Giao tiếp"),
    ("her", "/hɜː(r)/", "det, pron", "cô ấy, của cô ấy", "Her eyes are dark brown.", "Đôi mắt của cô ấy màu nâu sẫm.", "A1", "Gia đình"),
    ("she", "/ʃiː/", "pron", "cô ấy, bà ấy", "She is a kind teacher.", "Cô ấy là một giáo viên tốt bụng.", "A1", "Công việc & Công sở"),
    ("or", "/ɔː(r)/", "conj", "hoặc, hay là", "Tea or coffee for you?", "Trà hay cà phê cho bạn?", "A1", "Ăn uống"),
    ("an", "/æn/", "art", "một (trước nguyên âm)", "She ate an orange.", "Cô ấy đã ăn một quả cam.", "A1", "Ăn uống"),
    ("will", "/wɪl/", "v", "sẽ (tương lai)", "I will call you tonight.", "Tôi sẽ gọi cho bạn tối nay.", "A1", "Thời gian & Ngày tháng"),
    ("my", "/maɪ/", "det", "của tôi", "My mother is cooking.", "Mẹ tôi đang nấu ăn.", "A1", "Gia đình"),
    ("one", "/wʌn/", "num, pron", "số một, một", "Just one moment, please.", "Chỉ một lát thôi, làm ơn.", "A1", "Thời gian & Ngày tháng"),
    ("all", "/ɔːl/", "det, pron", "tất cả, toàn bộ", "All students passed the test.", "Tất cả học sinh đều qua bài kiểm tra.", "A1", "Giáo dục & Học tập"),
    ("would", "/wʊd/", "v", "muốn (lịch sự)", "I would like some water.", "Tôi muốn xin một chút nước.", "A1", "Ăn uống"),
    ("there", "/ðeə(r)/", "adv", "ở đằng kia, có", "There is a park nearby.", "Có một công viên ở gần đây.", "A1", "Đi lại & Du lịch"),
    ("their", "/ðeə(r)/", "det", "của họ", "Their house is large.", "Ngôi nhà của họ rất to.", "A1", "Nhà cửa & Đồ vật"),
    ("what", "/wɒt/", "pron", "cái gì, điều gì", "What is your dream?", "Ước mơ của bạn là gì?", "A1", "Chào hỏi & Giao tiếp"),
    ("so", "/səʊ/", "adv, conj", "vì vậy, rất", "It is so beautiful.", "Nó rất đẹp.", "A1", "Đời sống"),
    ("up", "/ʌp/", "adv, prep", "lên trên", "Wake up early in the morning.", "Thức dậy sớm vào buổi sáng.", "A1", "Đời sống"),
    ("out", "/aʊt/", "adv, prep", "ra ngoài", "Let's go out for dinner.", "Chúng ta ra ngoài ăn tối nhé.", "A1", "Ăn uống"),
    ("if", "/ɪf/", "conj", "nếu, liệu", "If you need help, tell me.", "Nếu bạn cần giúp đỡ, hãy bảo tôi.", "A1", "Đời sống"),
    ("about", "/əˈbaʊt/", "prep", "về, khoảng chừng", "Tell me about your job.", "Kể cho tôi nghe về công việc của bạn.", "A1", "Công việc & Công sở"),
    ("who", "/huː/", "pron", "ai, người nào", "Who is knocking on the door?", "Ai đang gõ cửa thế?", "A1", "Chào hỏi & Giao tiếp"),
    ("get", "/ɡet/", "v", "nhận được, trở nên", "Get ready for the exam.", "Hãy sẵn sàng cho kỳ thi.", "A1", "Đời sống"),
    ("which", "/wɪtʃ/", "pron, det", "cái nào, người nào", "Which color do you prefer?", "Bạn thích màu nào hơn?", "A1", "Mua sắm"),
    ("go", "/ɡəʊ/", "v", "đi, di chuyển", "I go to work by train.", "Tôi đi làm bằng tàu hỏa.", "A1", "Đi lại & Du lịch"),
    ("me", "/miː/", "pron", "tôi (tân ngữ)", "Give me your hand.", "Đưa tay bạn cho tôi.", "A1", "Chào hỏi & Giao tiếp"),
    ("when", "/wen/", "adv, conj", "khi nào", "When does the store open?", "Khi nào cửa hàng mở cửa?", "A1", "Thời gian & Ngày tháng"),
    ("make", "/meɪk/", "v", "làm, tạo ra", "Make a good decision.", "Hãy đưa ra quyết định sáng suốt.", "A1", "Đời sống"),
    ("can", "/kæn/", "v", "có thể", "Can you speak slowly?", "Bạn có thể nói chậm lại không?", "A1", "Chào hỏi & Giao tiếp"),
    ("like", "/laɪk/", "v, prep", "thích, giống như", "I like drinking hot tea.", "Tôi thích uống trà nóng.", "A1", "Ăn uống"),
    ("time", "/taɪm/", "n", "thời gian, lần", "What time is it now?", "Bây giờ là mấy giờ rồi?", "A1", "Thời gian & Ngày tháng"),
    ("no", "/nəʊ/", "det, int", "không", "No, I am not tired.", "Không, tôi không hề mệt.", "A1", "Chào hỏi & Giao tiếp"),
    ("just", "/dʒʌst/", "adv", "chỉ là, vừa mới", "Just give me five minutes.", "Chỉ cho tôi 5 phút thôi nhé.", "A1", "Thời gian & Ngày tháng"),
    ("him", "/hɪm/", "pron", "anh ấy (tân ngữ)", "I saw him at the library.", "Tôi nhìn thấy anh ấy ở thư viện.", "A1", "Gia đình"),
    ("know", "/nəʊ/", "v", "biết, hiểu", "I know the answer.", "Tôi biết câu trả lời.", "A1", "Đời sống"),
    ("take", "/teɪk/", "v", "lấy, cầm, tốn (thời gian)", "Take this medicine twice a day.", "Hãy uống thuốc này 2 lần một ngày.", "A1", "Sức khỏe & Y tế"),
    ("people", "/ˈpiːpl/", "n", "mọi người", "Vietnamese people are welcoming.", "Người Việt Nam rất mến khách.", "A1", "Gia đình"),
    ("into", "/ˈɪntuː/", "prep", "vào bên trong", "Walk into the living room.", "Bước vào trong phòng khách.", "A1", "Nhà cửa & Đồ vật"),
    ("year", "/jɪə(r)/", "n", "năm", "Happy New Year to you!", "Chúc bạn một năm mới vui vẻ!", "A1", "Thời gian & Ngày tháng"),
    ("your", "/jɔː(r)/", "det", "của bạn", "What is your phone number?", "Số điện thoại của bạn là gì?", "A1", "Chào hỏi & Giao tiếp"),
    ("good", "/ɡʊd/", "adj", "tốt đẹp, hay", "Have a good day!", "Chúc một ngày tốt lành!", "A1", "Chào hỏi & Giao tiếp"),
    ("some", "/sʌm/", "det, pron", "một vài, một ít", "Would you like some fruit?", "Bạn có muốn ăn chút hoa quả không?", "A1", "Ăn uống"),
    ("could", "/kʊd/", "v", "có thể (lịch sự)", "Could you help me, please?", "Bạn có thể giúp tôi được không?", "A1", "Chào hỏi & Giao tiếp"),
    ("them", "/ðem/", "pron", "họ, chúng (tân ngữ)", "Invite them to our party.", "Hãy mời họ đến bữa tiệc của chúng ta.", "A1", "Gia đình"),
    ("see", "/siː/", "v", "nhìn thấy, hiểu", "See you later!", "Hẹn gặp lại bạn sau nhé!", "A1", "Chào hỏi & Giao tiếp"),
    ("other", "/ˈʌðə(r)/", "adj, pron", "khác, người khác", "Do you have other colors?", "Bạn có các màu khác không?", "A1", "Mua sắm"),
    ("than", "/ðæn/", "prep, conj", "hơn (so sánh)", "Health is better than wealth.", "Sức khỏe quý hơn tiền tài.", "A1", "Sức khỏe & Y tế"),
    ("then", "/ðen/", "adv", "sau đó, lúc đó", "Wash your hands, then eat.", "Hãy rửa tay rồi sau đó mới ăn.", "A1", "Đời sống"),
    ("now", "/naʊ/", "adv", "bây giờ, ngay lúc này", "We are starting right now.", "Chúng ta bắt đầu ngay bây giờ.", "A1", "Thời gian & Ngày tháng"),
    ("look", "/lʊk/", "v, n", "nhìn ngắm, vẻ ngoài", "Look at that beautiful bird.", "Hãy nhìn chú chim xinh xắn kia kìa.", "A1", "Thời tiết & Thiên nhiên"),
    ("only", "/ˈəʊnli/", "adv, adj", "chỉ, duy nhất", "It takes only ten minutes.", "Chỉ mất có mười phút thôi.", "A1", "Thời gian & Ngày tháng"),
    ("come", "/kʌm/", "v", "đến, tới", "Come in and have a seat.", "Mời vào và ngồi xuống đây.", "A1", "Chào hỏi & Giao tiếp"),
    ("its", "/ɪts/", "det", "của nó", "The cat cleaned its fur.", "Con mèo tự liếm láp bộ lông của nó.", "A1", "Đời sống"),
    ("over", "/ˈəʊvə(r)/", "prep, adv", "qua, phía trên, kết thúc", "The meeting is over now.", "Cuộc họp đã kết thúc rồi.", "A1", "Công việc & Công sở"),
    ("think", "/θɪŋk/", "v", "suy nghĩ, cho rằng", "I think English is fun.", "Tôi nghĩ tiếng Anh rất thú vị.", "A1", "Chào hỏi & Giao tiếp"),
    ("also", "/ˈɔːlsəʊ/", "adv", "cũng, cũng như", "She also speaks French.", "Cô ấy cũng nói được tiếng Pháp.", "A1", "Chào hỏi & Giao tiếp"),
    ("back", "/bæk/", "adv, n", "quay lại, cái lưng", "I will be back in an hour.", "Tôi sẽ quay lại trong một tiếng nữa.", "A1", "Đi lại & Du lịch"),
    ("after", "/ˈɑːftə(r)/", "prep, conj", "sau khi", "Take a walk after dinner.", "Đi dạo một lát sau bữa tối.", "A1", "Thời gian & Ngày tháng"),
    ("use", "/juːz/", "v, n", "sử dụng, dùng", "Can I use your charger?", "Tôi có thể dùng củ sạc của bạn không?", "A1", "Công nghệ & Thiết bị"),
    ("two", "/tuː/", "num", "số hai", "Table for two, please.", "Cho một bàn hai người, làm ơn.", "A1", "Ăn uống"),
    ("how", "/haʊ/", "adv", "như thế nào, bằng cách nào", "How was your weekend?", "Cuối tuần của bạn như thế nào?", "A1", "Chào hỏi & Giao tiếp"),
    ("our", "/ˈaʊə(r)/", "det", "của chúng tôi", "Welcome to our home!", "Chào mừng đến với ngôi nhà của chúng tôi!", "A1", "Nhà cửa & Đồ vật"),
    ("work", "/wɜːk/", "v, n", "làm việc, công việc", "Hard work brings success.", "Làm việc chăm chỉ mang lại thành công.", "A1", "Công việc & Công sở"),
    ("first", "/fɜːst/", "num, adj", "đầu tiên, thứ nhất", "First, listen to the audio.", "Đầu tiên, hãy nghe đoạn âm thanh.", "A1", "Giáo dục & Học tập"),
    ("well", "/wel/", "adv, adj", "tốt, khỏe mạnh", "She sings very well.", "Cô ấy hát rất hay.", "A1", "Đời sống"),
    ("way", "/weɪ/", "n", "con đường, cách thức", "Can you show me the way?", "Bạn chỉ đường cho tôi được không?", "A1", "Đi lại & Du lịch"),
    ("even", "/ˈiːvn/", "adv", "thậm chí, ngay cả", "Even beginners can speak.", "Thậm chí người mới bắt đầu cũng có thể nói.", "A2", "Đời sống"),
    ("new", "/njuː/", "adj", "mới mẻ", "I bought a new pair of shoes.", "Tôi đã mua một đôi giày mới.", "A1", "Mua sắm"),
    ("want", "/wɒnt/", "v", "muốn", "I want to improve my speaking.", "Tôi muốn cải thiện kỹ năng nói của mình.", "A1", "Đời sống"),
    ("because", "/bɪˈkəz/", "conj", "bởi vì", "I study because I love it.", "Tôi học vì tôi rất yêu thích nó.", "A1", "Giáo dục & Học tập"),
    ("any", "/ˈeni/", "det, pron", "bất kỳ, nào", "Do you have any questions?", "Bạn có câu hỏi nào không?", "A1", "Chào hỏi & Giao tiếp"),
    ("these", "/ðiːz/", "pron, det", "những cái này", "These flowers smell sweet.", "Những bông hoa này thơm ngát.", "A1", "Thời tiết & Thiên nhiên"),
    ("give", "/ɡɪv/", "v", "cho, tặng", "Give me a call later.", "Hãy gọi điện cho tôi sau nhé.", "A1", "Chào hỏi & Giao tiếp"),
    ("day", "/deɪ/", "n", "ngày", "Have a wonderful day!", "Chúc bạn một ngày tuyệt vời!", "A1", "Thời gian & Ngày tháng"),
    ("most", "/məʊst/", "adv, det", "nhất, hầu hết", "Most people enjoy traveling.", "Hầu hết mọi người đều thích du lịch.", "A1", "Đi lại & Du lịch"),
    ("us", "/ʌs/", "pron", "chúng tôi (tân ngữ)", "Join us for lunch today.", "Hãy cùng ăn trưa với chúng tôi hôm nay.", "A1", "Ăn uống"),
]

print(f"Base Oxford top words loaded: {len(oxford_3000_raw)}")
